### ISSUE TITLE
configure-args equivalent for remotes::install_github or renv::install?

### ISSUE THREAD

**Issue by nick-youngblut** [wrathematics/openblasctl#1]
Thanks for creating this package! I hate how OpenBLAS will automatically use all 80 cores on our server (and hence all other users think you are a dick for hogging the server). 

OpenBLAS is installed in a weird location for me. I don't want to setup HPCRAN if not needed, and I use `renv::install` for installing all R packages, so it would be great if the README was updated with info on how to install openblasctl without using `install.packages("openblasctl", repos="https://hpcran.org", ...`. Do you know if `remotes::install_github` or `renv::install` has an equivalent to `configure-args`? I don't see any parameters named the same, so I'm not sure if `build_opts` in `remotes::install_github` is equivalent or not (and there's nothing similar for `renv::install`)

**Comment by wrathematics** [comment]
Not sure I understand the issue with HPCRAN. Could you elaborate?

You can pass additional arguments to `remotes::install_github()` (and I would guess `renv::install()` as well) that get passed to `install.packages()`. So you should be able to do something like:

```r
remotes::install_github("wrathematics/openblasctl", configure.args="--with-openblas-libpath=/path/to/openblas")
```

I will add a note to the readme about installing from different library paths.

**Comment by nick-youngblut** [comment]
> Not sure I understand the issue with HPCRAN. Could you elaborate?

This seems like an unnecessary step to set up HPCRAN, even if it is one command, especially given that I just want to use this one micro-package. Why is there a HPCRAN, when there's already CRAN? I wonder the same about bioconductor. A unified repository for all R packages seems more logical than multiple sub-repositories, possibly each with their own standards, methods of setting them up, etc. Then again, many developers are completely forgoing the CRAN submission process and just telling users to just install from GitHub. 

> You can pass additional arguments to remotes::install_github() (and I would guess renv::install() as well) 

I found out from https://github.com/rstudio/renv/issues/53 on how to do that for `renv::install`:

```
options(
  configure.args = list(
    openblasctl = "--with-openblas-libpath=/usr/local/opt/openblas/lib"
  )
)

renv::install("wrathematics/openblasctl")
```

However, when I use what I think is the correct path to openblas, I still get a `cannot find -lopenblas` error. The library path is listed in the session info, correct? For example:


```
sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS/LAPACK: /ebio/abt3_projects/my_project/envs/phyloseq/lib/libopenblasp-r0.3.7.so
```

...so I tried:


```
options(
  configure.args = list(
    openblasctl = "--with-openblas-libpath=/ebio/abt3_projects/my_project/envs/phyloseq/lib/"
  )
)

renv::install("wrathematics/openblasctl")
```

... but that still threw the same error.

I did end up trying `install.packages("openblasctl", repos="https://hpcran.org", configure-args="--with-openblas-libpath='/path/to/libopenblas/files/'")` after setting up HPCRAN, but got the following error: `Error: unexpected '=' in "install.packages("openblasctl", repos="https://hpcran.org", configure-args="`. It seems that R can't handle the `=` in the `configure.args` string.

**Comment by wrathematics** [comment]
So I still don't really understand what you mean when you say you need to set up HPCRAN. Let's table that for now.

There was a typo in the README where I had written `configure-args` instead of `configure.args` (it's `--configure-args` at the command line, but `configure.args` in `install.packages()`). But if `renv::install()` is failing saying it can't find `-lopenblas`, then something else is going on.

The issue is that the package is looking for a specific file, `libopenblas.so`. For now, could you try creating a symlink in your openblas directory?

```
cd /ebio/abt3_projects/my_project/envs/phyloseq/lib/
ln -s libopenblasp-r0.3.7.so libopenblas.so
```

I can change the package configure to allow for differently named libraries.

**Comment by nick-youngblut** [comment]
Note: conda does create a symlink file for `libopenblasp-r0.3.7.so`. It's named `libopenblasp-r0.3.7.so.0` instead of `libopenblasp-r0.3.7.so`

**Comment by nick-youngblut** [comment]
Just an FYI: creating the symlink `libopenblas.so.0 -> libopenblasp-r0.3.7.so` worked
